export * from './addon-doc.module';
export * from '@taiga-ui/addon-doc/components';
export * from '@taiga-ui/addon-doc/directives';
export * from '@taiga-ui/addon-doc/interfaces';
export * from '@taiga-ui/addon-doc/languages';
export * from '@taiga-ui/addon-doc/services';
export * from '@taiga-ui/addon-doc/tokens';
export * from '@taiga-ui/addon-doc/types';
export * from '@taiga-ui/addon-doc/utils';
