import {TUI_TRUE_HANDLER} from '@taiga-ui/cdk/constants';
import {tuiCreateTokenFromFactory} from '@taiga-ui/cdk/utils';

/**
 * @description:
 * The isTrusted read-only property of the Event interface is a boolean value that is true
 * when the event was generated by a user action, and false when the event was created or
 * modified by a script or dispatched via EventTarget.dispatchEvent().
 */
export const TUI_TAKE_ONLY_TRUSTED_EVENTS =
    tuiCreateTokenFromFactory<boolean>(TUI_TRUE_HANDLER);
