const ANGULAR_VERSION = `12.x.x`;

export const STACKBLITZ_DEPS: Record<string, string> = {
    '@angular/cdk': ANGULAR_VERSION,
    '@angular/core': ANGULAR_VERSION,
    '@angular/common': ANGULAR_VERSION,
    '@angular/compiler': ANGULAR_VERSION,
    '@angular/forms': ANGULAR_VERSION,
    '@angular/localize': ANGULAR_VERSION,
    '@angular/platform-browser': ANGULAR_VERSION,
    '@angular/platform-browser-dynamic': ANGULAR_VERSION,
    '@angular/animations': ANGULAR_VERSION,
    '@angular/router': ANGULAR_VERSION,
    '@taiga-ui/cdk': `*`,
    '@taiga-ui/i18n': `*`,
    '@taiga-ui/core': `*`,
    '@taiga-ui/kit': `*`,
    '@taiga-ui/icons': `*`,
    '@taiga-ui/styles': `*`,
    '@taiga-ui/addon-charts': `*`,
    '@taiga-ui/addon-commerce': `*`,
    '@taiga-ui/addon-mobile': `*`,
    '@taiga-ui/addon-table': `*`,
    '@taiga-ui/addon-tablebars': `*`,
    '@taiga-ui/addon-editor': `*`,
    '@tinkoff/ng-dompurify': `*`,
    '@tinkoff/ng-polymorpheus': `*`,
    '@ng-web-apis/common': `*`,
    '@tinkoff/ng-event-plugins': `*`,
    '@ng-web-apis/intersection-observer': `*`,
    '@ng-web-apis/mutation-observer': `*`,
    'text-mask-core': `*`,
    dompurify: `*`,
    '@types/dompurify': `*`,
    'prosemirror-state': `*`,
};
