codecov:
  branch: main
  max_report_age: off
  notify:
    require_ci_to_pass: no

coverage:
  range: 50..100
  round: down
  precision: 2
  status:
    project:
      default:
        enabled: false
    patch:
      default:
        enabled: false

comment: false

github_checks:
  annotations: false
