export const COLORED_ICONS = [
    'electron',
    'cirrus',
    'maestro',
    'mastercard',
    'mir',
    'visa',
    'union-pay',
    'jcb',
    'pay-pal',
    'amex',
    'diners-club',
    'discover',
    'humo',
    'ru-pay',
    'uzcard',
    'verve',
    'apple-pay',
    'google-pay',
    'samsung-pay',
    'world-pay',
    'ali-pay',
    'amazon-pay',
    'android-pay',
] as const;

export const MONO_ICONS = [
    '@tui.electron-mono',
    '@tui.maestro-mono',
    '@tui.mastercard-mono',
    '@tui.mir-mono',
    '@tui.visa-mono',
] as const;
