export const SEE_ALSO_GROUPS: ReadonlyArray<readonly string[]> = [
    ['Tooltip', 'Hint', 'HintManual', 'HintPointer'],
    ['LineChart', 'LineDaysChart'],
    ['Input', 'Textarea', 'InputChip'],
    ['InputDate', 'InputDateRange', 'InputMonth', 'InputDateTime', 'InputTime'],
    ['InputNumber', 'InputSlider', 'InputRange', 'Range', 'Slider'],
    ['InputCard', 'InputCardGroup'],
    ['Calendar', 'CalendarRange', 'MobileCalendar', 'CalendarMonth'],
    ['InputNumber', 'Money'],
    ['InputPhone', 'InputPhoneInternational'],
    ['Button', 'ButtonGroup', 'Link'],
    ['Checkbox', 'Radio', 'Switch', 'Block', 'Label'],
    ['Accordion', 'Expand'],
    ['ComboBox', 'MultiSelect', 'Select', 'ButtonSelect'],
    ['Badge', 'BadgedContent', 'Tag'],
    ['Dropdown', 'DropdownSelection', 'DropdownHover', 'DropdownContext', 'DropdownOpen'],
    ['ProgressBar', 'ProgressCircle', 'ProgressSegmented', 'Loader'],
    ['Preview', 'PdfViewer'],
    ['Table', 'TablePagination', 'TableFilters'],
    ['SheetDialog', 'Dialog', 'BottomSheet'],
];
