export const enum TuiCurrency {
    Ruble = 'RUB',
    Euro = 'EUR',
    Dollar = 'USD',
    Pound = 'GBP',
    Baht = 'THB',
    TurkishLira = 'TRY',
    YuanRenminbi = 'CNY',
    Tenge = 'KZT',
    IsraeliShekel = 'ILS',
    IndianRupee = 'INR',
    Yen = 'JPY',
    SwissFranc = 'CHF',
    SingaporeDollar = 'SGD',
    AustralianDollar = 'AUD',
    HongKong_dollar = 'HKD',
    CanadianDollar = 'CAD',
    ArmenianDram = 'AMD',
    Won = 'KRW',
    Hryvnia = 'UAH',
}
