export const IGNORABLE_TAIGA_PACKAGES = [
    '@taiga-ui/browserslist-config',
    '@taiga-ui/commitlint-config',
    '@taiga-ui/cspell-config',
    '@taiga-ui/design-tokens',
    '@taiga-ui/dompurify',
    '@taiga-ui/editor',
    '@taiga-ui/eslint-plugin-experience',
    '@taiga-ui/event-plugins',
    '@taiga-ui/jest-config',
    '@taiga-ui/polymorpheus',
    '@taiga-ui/prettier-config',
    '@taiga-ui/stylelint-config',
    '@taiga-ui/tsconfig',
] as const;
