import {TuiBaseColor, TuiColor, TuiSupportColor} from '@taiga-ui/core';

/** @deprecated */
export const DEFAULT_COLORS: ReadonlyArray<TuiColor | string> = [
    TuiBaseColor.Primary,
    TuiSupportColor.Havelock,
    TuiSupportColor.Feijoa,
    TuiSupportColor.Lilac,
    `base-05`,
    TuiSupportColor.Mustard,
    TuiSupportColor.Texas,
    TuiSupportColor.Tan,
    TuiSupportColor.Salmon,
    TuiSupportColor.Sienna,
    TuiSupportColor.Bittersweet,
    TuiSupportColor.Pinkie,
    TuiSupportColor.Charm,
    TuiSupportColor.Amethist,
    TuiSupportColor.Helio,
    TuiSupportColor.Malibu,
    TuiSupportColor.Picton,
    TuiSupportColor.Mint,
    TuiSupportColor.Fountain,
    TuiSupportColor.Puertorico,
    TuiSupportColor.Bay,
    TuiSupportColor.Forest,
    TuiSupportColor.York,
    TuiBaseColor.Error,
    TuiBaseColor.Success,
    TuiBaseColor.Secondary,
];
