name: '🐞 - Bug Report'
title: '🐞 - '
description: Report a bug in the Taiga UI
labels: ['bug', 'state: need triage']

body:
  - type: dropdown
    id: affected-packages
    attributes:
      label: Which @taiga-ui/* package(s) are the source of the bug?
      options:
        - core
        - kit
        - cdk
        - i18n
        - icons
        - taiga-schematics
        - testing
        - addon-charts
        - addon-commerce
        - addon-doc
        - addon-editor
        - addon-mobile
        - addon-table
        - addon-tablebars
        - Don't known / other
      multiple: true
    validations:
      required: true

  - type: input
    id: reproduction-url
    attributes:
      label: Please provide a link to a minimal reproduction of the bug
      value: https://stackblitz.com/edit/taiga-starter

  - type: dropdown
    id: blocking
    attributes:
      label: Is this issue blocking you?
      options:
        - Non-Blocking
        - Blocking
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Please provide the exception or error you saw.
    validations:
      required: true

  - type: input
    id: angular-version
    attributes:
      label: Angular version
      placeholder: x.y.z
    validations:
      required: true

  - type: input
    id: taiga-version
    attributes:
      label: Taiga UI version
      placeholder: x.y.z
    validations:
      required: true

  - type: checkboxes
    id: browser-specific
    attributes:
      label: Which browsers have you used?
      description: You may select more than one.
      options:
        - label: Chrome
        - label: Firefox
        - label: Safari
        - label: Edge

  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which operating systems have you used?
      description: You may select more than one.
      options:
        - label: macOS
        - label: Windows
        - label: Linux
        - label: iOS
        - label: Android
