name: '📚 - Docs or taiga-ui.dev Bug Report'
title: '📚 - '
description: Report an issue in Taiga's documentation or taiga-ui.dev application
labels: ['documentation', 'state: need triage']

body:
  - type: input
    id: affected-url
    attributes:
      label: What is the affected URL?

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        How do you trigger this bug?
        Please walk us through it step by step.
        Please provide a screenshot if possible.
    validations:
      required: true

  - type: checkboxes
    id: browser-specific
    attributes:
      label: Which browsers have you used?
      description: You may select more than one.
      options:
        - label: Chrome
        - label: Firefox
        - label: Safari
        - label: Edge
    validations:
      required: true

  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which operating systems have you used?
      description: You may select more than one.
      options:
        - label: macOS
        - label: Windows
        - label: Linux
        - label: iOS
        - label: Android
    validations:
      required: true
