name: '🤖 - Dev Infrastructure Request'
title: '🤖 - '
description: Suggest a feature for improve productivity of the Taiga UI Team
labels: ['dev-infra', 'state: need triage']

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Proposed solution.
        Alternatives considered.
    validations:
      required: true
