import {Component} from '@angular/core';
import {changeDetection} from '@demo/emulate/change-detection';
import {encapsulation} from '@demo/emulate/encapsulation';
import {TUI_FILTER_BY_INPUT_OPTIONS} from '@taiga-ui/kit';

@Component({
    selector: `tui-combo-box-example-5`,
    templateUrl: `./index.html`,
    styleUrls: [`./index.less`],
    changeDetection,
    encapsulation,
    providers: [
        {
            provide: TUI_FILTER_BY_INPUT_OPTIONS,
            useValue: {
                strictMode: false,
            },
        },
    ],
})
export class TuiComboBoxExample5 {
    value = null;

    readonly countries = [
        `Afghanistan`,
        `Albania`,
        `Algeria`,
        `American Samoa`,
        `Andorra`,
        `Angola`,
        `Anguilla`,
        `Antarctica`,
        `Antigua and Barbuda`,
        `Argentina`,
        `Armenia`,
        `Aruba`,
        `Australia`,
        `Austria`,
        `Azerbaijan`,
        `Bahamas`,
        `Bahrain`,
        `Bangladesh`,
        `Barbados`,
        `Belarus`,
        `Belgium`,
        `Belize`,
        `Benin`,
        `Bermuda`,
        `Bhutan`,
        `Bolivia`,
        `Bonaire, Sint Eustatius and Saba`,
        `Bosnia and Herzegovina`,
        `Botswana`,
        `Bouvet Island`,
        `Brazil`,
        `British Indian Ocean Territory`,
        `Brunei Darussalam`,
        `Bulgaria`,
        `Burkina Faso`,
        `Burundi`,
        `Cabo Verde`,
        `Cambodia`,
        `Cameroon`,
        `Canada`,
        `Cayman Islands`,
        `Central African Republic`,
        `Chad`,
        `Chile`,
        `China`,
        `Christmas Island`,
        `Cocos (Keeling) Islands`,
        `Colombia`,
        `Comoros`,
        `Congo`,
        `Cook Islands`,
        `Costa Rica`,
        `Croatia`,
        `Cuba`,
        `Curaçao`,
        `Cyprus`,
        `Czechia`,
        `Côte d'Ivoire`,
        `Denmark`,
        `Djibouti`,
        `Dominica`,
        `Dominican Republic`,
        `Ecuador`,
        `Egypt`,
        `El Salvador`,
        `Equatorial Guinea`,
        `Eritrea`,
        `Estonia`,
        `Eswatini`,
        `Ethiopia`,
        `Falkland Islands`,
        `Faroe Islands`,
        `Fiji`,
        `Finland`,
        `France`,
        `French Guiana`,
        `French Polynesia`,
        `French Southern Territories`,
        `Gabon`,
        `Gambia`,
        `Georgia`,
        `Germany`,
        `Ghana`,
        `Gibraltar`,
        `Greece`,
        `Greenland`,
        `Grenada`,
        `Guadeloupe`,
        `Guam`,
        `Guatemala`,
        `Guernsey`,
        `Guinea`,
        `Guinea-Bissau`,
        `Guyana`,
        `Haiti`,
        `Heard Island and McDonald Islands`,
        `Holy See`,
        `Honduras`,
        `Hong Kong`,
        `Hungary`,
        `Iceland`,
        `India`,
        `Indonesia`,
        `Iran`,
        `Iraq`,
        `Ireland`,
        `Isle of Man`,
        `Israel`,
        `Italy`,
        `Jamaica`,
        `Japan`,
        `Jersey`,
        `Jordan`,
        `Kazakhstan`,
        `Kenya`,
        `Kiribati`,
        `Korea`,
        `Kuwait`,
        `Kyrgyzstan`,
        `Lao People's Democratic Republic`,
        `Latvia`,
        `Lebanon`,
        `Lesotho`,
        `Liberia`,
        `Libya`,
        `Liechtenstein`,
        `Lithuania`,
        `Luxembourg`,
        `Macao`,
        `Madagascar`,
        `Malawi`,
        `Malaysia`,
        `Maldives`,
        `Mali`,
        `Malta`,
        `Marshall Islands`,
        `Martinique`,
        `Mauritania`,
        `Mauritius`,
        `Mayotte`,
        `Mexico`,
        `Micronesia`,
        `Moldova`,
        `Monaco`,
        `Mongolia`,
        `Montenegro`,
        `Montserrat`,
        `Morocco`,
        `Mozambique`,
        `Myanmar`,
        `Namibia`,
        `Nauru`,
        `Nepal`,
        `Netherlands`,
        `New Caledonia`,
        `New Zealand`,
        `Nicaragua`,
        `Niger`,
        `Nigeria`,
        `Niue`,
        `Norfolk Island`,
        `Northern Mariana Islands`,
        `Norway`,
        `Oman`,
        `Pakistan`,
        `Palau`,
        `Palestine, State of`,
        `Panama`,
        `Papua New Guinea`,
        `Paraguay`,
        `Peru`,
        `Philippines`,
        `Pitcairn`,
        `Poland`,
        `Portugal`,
        `Puerto Rico`,
        `Qatar`,
        `Republic of North Macedonia`,
        `Romania`,
        `Russian Federation`,
        `Rwanda`,
        `Réunion`,
        `Saint Barthélemy`,
        `Saint Helena`,
        `Saint Kitts and Nevis`,
        `Saint Lucia`,
        `Saint Martin`,
        `Saint Pierre and Miquelon`,
        `Saint Vincent and the Grenadines`,
        `Samoa`,
        `San Marino`,
        `Sao Tome and Principe`,
        `Saudi Arabia`,
        `Senegal`,
        `Serbia`,
        `Seychelles`,
        `Sierra Leone`,
        `Singapore`,
        `Sint Maarten (Dutch part)`,
        `Slovakia`,
        `Slovenia`,
        `Solomon Islands`,
        `Somalia`,
        `South Africa`,
        `South Georgia`,
        `South Sudan`,
        `Spain`,
        `Sri Lanka`,
        `Sudan`,
        `Suriname`,
        `Svalbard and Jan Mayen`,
        `Sweden`,
        `Switzerland`,
        `Syrian Arab Republic`,
        `Taiwan`,
        `Tajikistan`,
        `Tanzania, United Republic of`,
        `Thailand`,
        `Timor-Leste`,
        `Togo`,
        `Tokelau`,
        `Tonga`,
        `Trinidad and Tobago`,
        `Tunisia`,
        `Turkey`,
        `Turkmenistan`,
        `Turks and Caicos Islands`,
        `Tuvalu`,
        `Uganda`,
        `Ukraine`,
        `United Arab Emirates`,
        `United Kingdom`,
        `United States of America`,
        `Uruguay`,
        `Uzbekistan`,
        `Vanuatu`,
        `Venezuela`,
        `Viet Nam`,
        `Virgin Islands (British)`,
        `Virgin Islands (U.S.)`,
        `Wallis and Futuna`,
        `Western Sahara`,
        `Yemen`,
        `Zambia`,
        `Zimbabwe`,
        `Åland Islands`,
    ];
}
