import {ChangeDetectionStrategy, Component, inject} from '@angular/core';
import {tuiPure} from '@taiga-ui/cdk';
import {POLYMORPHEUS_CONTEXT} from '@tinkoff/ng-polymorpheus';

const HINT_CONTROLLER_SELECTORS = ['tuiHintContent'];

const TEXTFIELD_CONTROLLER_SELECTORS = [
    'tuiTextfieldCleaner',
    'tuiTextfieldCustomContent',
    'tuiTextfieldLabelOutside',
    'tuiTextfieldSize',
];

const DROPDOWN_CONTROLLER_SELECTORS = [
    'tuiDropdownAlign',
    'tuiDropdownDirection',
    'tuiDropdownLimitWidth',
    'tuiDropdownMinHeight',
    'tuiDropdownMaxHeight',
    'tuiDropdownOffset',
];

@Component({
    selector: 'tui-autogenerated-code-hints',
    templateUrl: './autogenerated-code-hints.template.html',
    styleUrls: ['./autogenerated-code-hints.style.less'],
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TuiAutoGeneratedCodeHintsComponent {
    protected readonly context = inject(POLYMORPHEUS_CONTEXT);

    protected get code(): string {
        return this.context.$implicit;
    }

    @tuiPure
    protected shouldShowIcon(code: string): boolean {
        return (
            this.includesHintController(code) ||
            this.includesTextfieldController(code) ||
            this.includesDropdownController(code) ||
            this.includesDataListWrapper(code)
        );
    }

    @tuiPure
    protected includesHintController(code: string): boolean {
        return HINT_CONTROLLER_SELECTORS.some(selector => code.includes(selector));
    }

    @tuiPure
    protected includesTextfieldController(code: string): boolean {
        return TEXTFIELD_CONTROLLER_SELECTORS.some(selector => code.includes(selector));
    }

    @tuiPure
    protected includesDropdownController(code: string): boolean {
        return DROPDOWN_CONTROLLER_SELECTORS.some(selector => code.includes(selector));
    }

    @tuiPure
    protected includesDataListWrapper(code: string): boolean {
        return code.includes('<tui-data-list-wrapper');
    }
}
