export const TUI_CYPRESS_MOBILE_USER_AGENT = `Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1`;
export const TUI_CYPRESS_MOBILE_VIEWPORT_WIDTH = 390;
export const TUI_CYPRESS_MOBILE_VIEWPORT_HEIGHT = 840;
export const TUI_CYPRESS_DESKTOP_VIEWPORT_WIDTH = 1440;
export const TUI_CYPRESS_DESKTOP_VIEWPORT_HEIGHT = 900;
