import {
    tuiIconAlertCircle,
    tuiIconArrowRight,
    tuiIconAttention,
    tuiIconCalendar,
    tuiIconCancel,
    tuiIconCheck,
    tuiIconCheckCircle,
    tuiIconChevronDown,
    tuiIconChevronLeft,
    tuiIconClose,
    tuiIconHide,
    tuiIconInfoCircle,
    tuiIconMinus,
    tuiIconMoreVert,
    tuiIconPlus,
    tuiIconRemove,
    tuiIconSearch,
    tuiIconShow,
    tuiIconTime,
    tuiIconToggleOff,
    tuiIconTooltip,
    tuiIconTrash,
} from '../all';

export const tuiCoreIcons = {
    tuiIconArrowRight,
    tuiIconAttention,
    tuiIconCancel,
    tuiIconCheck,
    tuiIconClose,
    tuiIconRemove,
    tuiIconInfoCircle,
    tuiIconMinus,
    tuiIconTooltip,
};

export const tuiKitIcons = {
    ...tuiCoreIcons,
    tuiIconAlertCircle,
    tuiIconChevronDown,
    tuiIconChevronLeft,
    tuiIconCalendar,
    tuiIconCheckCircle,
    tuiIconHide,
    tuiIconMoreVert,
    tuiIconPlus,
    tuiIconSearch,
    tuiIconShow,
    tuiIconTime,
    tuiIconToggleOff,
    tuiIconTrash,
};
