import {
    tuiIconAlertCircleLarge,
    tuiIconArrowRight,
    tuiIconAttention,
    tuiIconCalendar,
    tuiIconCalendarLarge,
    tuiIconCancel,
    tuiIconCheck,
    tuiIconCheckCircleLarge,
    tuiIconCheckLarge,
    tuiIconChevronDown,
    tuiIconChevronDownLarge,
    tuiIconChevronLeft,
    tuiIconCloseLarge,
    tuiIconHideLarge,
    tuiIconInfo,
    tuiIconMinus,
    tuiIconMinusLarge,
    tuiIconMoreVer,
    tuiIconPlus,
    tuiIconRemoveLarge,
    tuiIconSearchLarge,
    tuiIconShowLarge,
    tuiIconTime,
    tuiIconTimeLarge,
    tuiIconToggleOff,
    tuiIconToggleOffLarge,
    tuiIconTooltip,
    tuiIconTrashLarge,
} from '../all';

export const tuiCoreIcons = {
    tuiIconArrowRight,
    tuiIconAttention,
    tuiIconCancel,
    tuiIconCheck,
    tuiIconCheckLarge,
    tuiIconCloseLarge,
    tuiIconRemoveLarge,
    tuiIconInfo,
    tuiIconMinus,
    tuiIconMinusLarge,
    tuiIconTooltip,
};

export const tuiKitIcons = {
    ...tuiCoreIcons,
    tuiIconAlertCircleLarge,
    tuiIconChevronDown,
    tuiIconChevronDownLarge,
    tuiIconChevronLeft,
    tuiIconCalendar,
    tuiIconCalendarLarge,
    tuiIconCheckCircleLarge,
    tuiIconHideLarge,
    tuiIconMoreVer,
    tuiIconPlus,
    tuiIconSearchLarge,
    tuiIconShowLarge,
    tuiIconTime,
    tuiIconTimeLarge,
    tuiIconToggleOff,
    tuiIconToggleOffLarge,
    tuiIconTrashLarge,
};
