module.exports = {
    overrides: [
        {
            files: ['*.ts'],
            parser: '@typescript-eslint/parser',
            plugins: ['@typescript-eslint'],
            rules: {
                // TODO: move to @tinkoff/eslint-config-angular
                '@typescript-eslint/no-useless-constructor': 'off',
                'no-prototype-builtins': 'off',
                '@typescript-eslint/no-shadow': 'off',
                '@typescript-eslint/no-var-requires': 'off',
                '@typescript-eslint/no-non-null-assertion': 'off',
                '@typescript-eslint/no-empty-function': 'off',
                '@typescript-eslint/ban-ts-comment': 'off',
                'eslint-comments/no-unlimited-disable': 'off',
                'eslint-comments/disable-enable-pair': 'off',
                'import/no-dynamic-require': 'off',
                'promise/catch-or-return': 'off',
                'spaced-comment': 'off',
                'max-nested-callbacks': 'off',
                'import/no-deprecated': 'off',
                'promise/no-nesting': 'off',
                'no-loop-func': 'off',
                'no-bitwise': 'off',
                quotes: 'off',
            },
        },
        {
            // TODO: enable later
            files: ['*'],
            rules: {
                radix: 'off',
                complexity: 'off',
                'import/no-cycle': 'off',
                'no-return-await': 'off',
                'rxjs/no-topromise': 'off',
                'import/no-named-default': 'off',
                'no-useless-concat': 'off',
                'max-statements': 'off',
                'import/no-unresolved': 'off',
                '@typescript-eslint/require-await': 'off',
                '@typescript-eslint/no-base-to-string': 'off',
                '@html-eslint/no-duplicate-id': 'off',
                '@html-eslint/no-target-blank': 'off',
                '@html-eslint/no-multiple-h1': 'off',
                '@html-eslint/require-img-alt': 'off',
                '@html-eslint/no-inline-styles': 'off',
                '@html-eslint/require-frame-title': 'off',
                '@html-eslint/id-naming-convention': 'off',
            },
        },
    ],
};
