name: Taiga-UI action for Node.js
description: Node.js setup cache

inputs:
  node-version:
    description: Node.js version
    required: false
    default: 14.x

runs:
  using: composite
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - name: Restore node_modules from cache
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          */*/node_modules/
          !node_modules/.cache
          !*/*/node_modules/.cache
        key: modules-cache__nodejs-${{ inputs.node-version }}__${{ hashfiles('**/package-lock.json') }}

    - name: Restore from cache of builds
      id: build-cache
      if: steps.cache-node-modules.outputs.cache-hit == 'true'
      uses: actions/cache@v3
      with:
        path: |
          node_modules/.cache
          */*/node_modules/.cache
        key: builds-cache-hash__${{ hashFiles('**/package-lock.json') }}-${{ github.ref }}
        restore-keys: builds-cache__nodejs-${{ inputs.node-version }}__${{ hashFiles('**/package-lock.json') }}

    - name: Restore from global NPM cache
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-cache__nodejs-${{ inputs.node-version }}__${{ hashFiles('**/package-lock.json') }}
        restore-keys: npm-cache-hash__

    - run: npm ci
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
