/**
 * @description:
 * AUTOGENERATED
 *
 * Array of icons used in ./projects/demo-playwright
 */
export const TUI_USED_ICONS = [
    '@tui.calendar',
    '@tui.eye-off',
    '@tui.lock',
    '@tui.snowflake',
] as const;
