export * from '@taiga-ui/core/pipes/auto-color';
export * from '@taiga-ui/core/pipes/calendar-sheet';
export * from '@taiga-ui/core/pipes/fallback-src';
export * from '@taiga-ui/core/pipes/flag';
export * from '@taiga-ui/core/pipes/format-date';
export * from '@taiga-ui/core/pipes/format-number';
export * from '@taiga-ui/core/pipes/initials';
export * from '@taiga-ui/core/pipes/month';
export * from '@taiga-ui/core/pipes/order-week-days';
