{
    const path = require('node:path');
    const fs = require('node:fs');

    (function main(): void {
        const src = path.join(process.cwd(), 'projects', 'icons', 'src');
        const allIconsPath = path.join(process.cwd(), 'projects', 'icons');
        const allIcons: string[] = [];

        fs.readdirSync(src).forEach((filename: string) => {
            if (filename !== 'flags') {
                allIcons.push(filename.split('.')[0]);
            }
        });

        fs.writeFileSync(
            path.join(allIconsPath, 'all-icons.ts'),
            `/**
 * @description:
 * AUTOGENERATED
 *
 * Array of icons
 */
 export const TUI_ALL_ICONS = ${JSON.stringify(allIcons)} as const`,
        );
    })();
}
