export const SEE_ALSO_GROUPS: ReadonlyArray<readonly string[]> = [
    ['Tooltip', 'Hint', 'HintManual', 'HintPointer'],
    ['LineChart', 'LineDaysChart'],
    ['PrimitiveTextfield', 'Input', 'Textarea'],
    [
        'InputDate',
        'InputDateRange',
        'InputMonth',
        'InputMonthRange',
        'InputDateTime',
        'InputTime',
    ],
    ['InputNumber', 'InputSlider', 'InputRange', 'Range', 'Slider'],
    ['InputCard', 'InputCardGroup'],
    ['Calendar', 'CalendarRange', 'MobileCalendar', 'CalendarMonth'],
    ['Error', 'FieldError'],
    ['InputNumber', 'Money'],
    ['InputPhone', 'InputPhoneInternational'],
    ['Button', 'ButtonVertical', 'ButtonGroup', 'Action', 'Link'],
    ['Action', 'Island'],
    ['Checkbox', 'Radio', 'Switch', 'Block', 'Label'],
    ['Accordion', 'Expand'],
    ['ComboBox', 'MultiSelect', 'Select'],
    ['Badge', 'BadgedContent', 'Tag'],
    ['Notification', 'AlertService'],
    ['Scrollbar', 'ScrollService'],
    ['Dropdown', 'DropdownSelection', 'DropdownHover', 'DropdownContext', 'DropdownOpen'],
    ['ProgressBar', 'ProgressCircle', 'ProgressSegmented', 'Loader'],
    ['Preview', 'PdfViewer'],
    ['Table', 'TablePagination', 'TableFilters'],
];
