export const SEE_ALSO_GROUPS: ReadonlyArray<readonly string[]> = [
    [`Tooltip`, `Hint`, `HintManual`, `HintPointer`],
    [`LineChart`, `LineDaysChart`],
    [`PrimitiveTextfield`, `Input`, `TextArea`],
    [
        `InputDate`,
        `InputDateRange`,
        `InputMonth`,
        `InputMonthRange`,
        `InputDateTime`,
        `InputTime`,
    ],
    [`InputNumber`, `InputCount`, `InputSlider`, `InputRange`, `Range`, `Slider`],
    [`InputCard`, `InputCardGrouped`],
    [`Calendar`, `CalendarRange`, `MobileCalendar`, `CalendarMonth`],
    [`Error`, `FieldError`],
    [`InputNumber`, `Money`],
    [`InputPhone`, `InputPhoneInternational`],
    [`Button`, `Action`, `Link`],
    [`CheckboxBlock`, `CheckboxLabeled`, `PrimitiveCheckbox`, `Toggle`, `Checkbox`],
    [`Accordion`, `Expand`],
    [`Radio`, `RadioBlock`, `RadioLabeled`, `RadioList`],
    [`ComboBox`, `MultiSelect`, `Select`],
    [`Badge`, `BadgedContent`, `Tag`],
    [`Notification`, `AlertService`],
    [`Scrollbar`, `ScrollService`],
    [`Dropdown`, `DropdownSelection`, `HostedDropdown`],
    [`ProgressBar`, `ProgressCircle`, `ProgressSegmented`, `Loader`],
    [`Preview`, `PdfViewer`],
    [`Icons`, `Svg`, `SvgService`, `MarkerIcon`],
    [`Table`, `TablePagination`, `TableFilters`],
];
