export type TuiPaymentSystem =
    | 'amex'
    | 'dinersclub'
    | 'discover'
    | 'electron'
    | 'humo'
    | 'jcb'
    | 'maestro'
    | 'mastercard'
    | 'mir'
    | 'rupay'
    | 'unionpay'
    | 'uzcard'
    | 'verve'
    | 'visa';
