name: 🤖 PR author as an assignee
on:
  pull_request:
    types: [opened]

permissions:
  contents: read
  pull-requests: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: taiga-family/ci/actions/setup/variables@v1.195.0
      - uses: toshimaru/auto-author-assign@v3.0.1
        continue-on-error: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
