name: 🤖 PR auto merge
on:
  pull_request:

permissions:
  actions: read
  contents: read
  pull-requests: write

env:
  PR_JOBS_NAME: '[ "Build packages", "Firebase", "Lint", "Tests result", "E2E result" ]'
  RELEASE_JOBS_NAME: '[ "Publish" ]'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: taiga-family/ci/actions/setup/variables@e9c5cd341c28d9aeb357b757df41cddcbb674b2d # v1.222.0
      - id: matrix
        if: env.IS_TAIGA_FAMILY_BOT_PR_AUTHOR == 'true'
        run: |
          if [[ "${{ env.IS_RELEASE_BRANCH }}" == "false" ]]; then
              echo "value=$PR_JOBS_NAME" >> $GITHUB_OUTPUT
          else
            echo "value=$RELEASE_JOBS_NAME" >> $GITHUB_OUTPUT
          fi

  wait:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        value: ${{ fromJSON(needs.setup.outputs.matrix || '[]') }}
    steps:
      - uses: taiga-family/ci/actions/run/wait-job@e9c5cd341c28d9aeb357b757df41cddcbb674b2d # v1.222.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          job: ${{ matrix.value }}

  approve:
    needs: [wait]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: taiga-family/ci/actions/setup/variables@e9c5cd341c28d9aeb357b757df41cddcbb674b2d # v1.222.0
      - uses: taiga-family/ci/actions/auto/approve/double@e9c5cd341c28d9aeb357b757df41cddcbb674b2d # v1.222.0
        if: env.IS_TAIGA_FAMILY_BOT_PR_AUTHOR == 'true'
        with:
          token1: ${{ secrets.GITHUB_TOKEN }}
          token2: ${{ secrets.TAIGA_FAMILY_APPROVE_BOT_PAT }}
      - uses: taiga-family/ci/actions/run/merge@e9c5cd341c28d9aeb357b757df41cddcbb674b2d # v1.222.0
        if: env.IS_TAIGA_FAMILY_BOT_PR_AUTHOR == 'true'
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          merge-method: ${{ (contains(github.head_ref, 'release/') && 'merge') || 'squash' }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
