name: 🤖 Community contribution
on:
  pull_request_target:
    types: [closed]

jobs:
  add-label:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.repo.fork == true
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: taiga-family/ci/actions/auto/label-community-contribution@a173bbdd44beec5cb34444b6fa497284da803031 # v1.217.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.pull_request.number }}
          label-name: community contribution
