name: 🤖 Auto update used icons
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bundling:
    if: ${{ !contains(github.head_ref , 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: taiga-family/actions/setup-variables@2446a1d329acc075f7264292facddf0b0c992b53 # v2.1.0
      - uses: taiga-family/actions/setup-node@2446a1d329acc075f7264292facddf0b0c992b53 # v2.1.0
      - run: |
          npx ts-node ./scripts/generate-used-icons.ts
          npx eslint ./projects/cdk/constants/used-icons.ts --fix || echo "no file matching"
          npx eslint ./projects/demo/used-icons.ts --fix || echo "no file matching"
          npx eslint ./projects/demo-playwright/used-icons.ts --fix || echo "no file matching"
          npx prettier ./projects/demo/used-icons.ts --write || echo "no file matching"
          npx prettier ./projects/demo-playwright/used-icons.ts --write || echo "no file matching"
          npx prettier ./projects/cdk/constants/used-icons.ts --write || echo "no file matching"
      - uses: taiga-family/actions/auto-push@2446a1d329acc075f7264292facddf0b0c992b53 # v2.1.0
        if: env.SUPPORT_AUTO_PUSH
        with:
          message: icons have changed
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
