name: 🤖 Community contribution
on:
  pull_request_target:
    types: [closed]

jobs:
  add-label:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.repo.fork == true
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: taiga-family/actions/auto-label-community-contribution@a12b79beab3aea8bd840e48e902a2084d282e1a6 # v2.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.pull_request.number }}
          label-name: community contribution
