name: ⚙️ Build
on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  libs:
    if: ${{ !contains(github.head_ref, 'release/') }}
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: taiga-family/actions/setup-variables@a11d89eb978fe572206a7b0a026b38ae957acba0 # v2.0.0
      - uses: taiga-family/actions/setup-node@a11d89eb978fe572206a7b0a026b38ae957acba0 # v2.0.0
      - run: npm run run-many:build:libs
      - run: npx ts-node ./scripts/check-dist.ts

  demo:
    if: ${{ !contains(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: taiga-family/actions/setup-variables@a11d89eb978fe572206a7b0a026b38ae957acba0 # v2.0.0
      - uses: taiga-family/actions/setup-node@a11d89eb978fe572206a7b0a026b38ae957acba0 # v2.0.0
      - run: npx nx build demo
      - run: npx --yes bundlemon --config .github/.bundlemonrc.json
        continue-on-error: true
        env:
          CI_COMMIT_SHA: ${{ env.CI_COMMIT_SHA }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
