name: ⚙️ Build
on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  libs:
    if: ${{ !contains(github.head_ref, 'release/') }}
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: taiga-family/ci/actions/setup/variables@44fd3eb3c46e9e6c39fd3820479c467aa75c8028 # v1.221.0
      - uses: taiga-family/ci/actions/setup/node@44fd3eb3c46e9e6c39fd3820479c467aa75c8028 # v1.221.0
      - run: npm run run-many:build:libs
      - run: npx ts-node ./scripts/check-dist.ts

  demo:
    if: ${{ !contains(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: taiga-family/ci/actions/setup/variables@44fd3eb3c46e9e6c39fd3820479c467aa75c8028 # v1.221.0
      - uses: taiga-family/ci/actions/setup/node@44fd3eb3c46e9e6c39fd3820479c467aa75c8028 # v1.221.0
      - run: npx nx build demo
      - run: npx --yes bundlemon --config .github/.bundlemonrc.json
        continue-on-error: true
        env:
          CI_COMMIT_SHA: ${{ env.CI_COMMIT_SHA }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
