name: ⚠️ Create release
on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: release type
        required: true
        default: minor
        options:
          - patch
          - minor
          - prerelease
          - major
      dry_run:
        type: boolean
        description: dry run
        required: true
        default: false

jobs:
  run-release:
    name: Run release
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Print selected mode
        run: |
          echo "mode=${{ inputs.mode }}"
          echo "dry_run=${{ inputs.dry_run }}"
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
      - uses: taiga-family/ci/actions/setup/node@41a6dcaf21b0a83a93310de63dde18583feb5920 # v1.210.0
      - uses: taiga-family/ci/actions/setup/config/git@41a6dcaf21b0a83a93310de63dde18583feb5920 # v1.210.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

      - name: Run release
        id: run-release
        shell: bash
        run: |
          npx ts-node ./scripts/release.ts \
            --ci-mode \
            --release-as ${{ inputs.mode }} \
            ${{ inputs.dry_run && '--dry-run true' || '' }}

          echo "new_version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"

      - name: Generate Release Body
        if: ${{ !inputs.dry_run && inputs.mode != 'prerelease' }}
        id: generate_body
        run: |
          npx extract-changelog-release > RELEASE_BODY.md
          echo "tag_name=$(git describe --abbrev=0 --tags)" >> "$GITHUB_OUTPUT"

      - name: Get PR body
        if: ${{ !inputs.dry_run && inputs.mode != 'prerelease' }}
        id: get-pr-body
        shell: bash
        run: |
          body=$(cat RELEASE_BODY.md)
          delimiter="$(openssl rand -hex 8)"
          echo "body<<$delimiter" >> $GITHUB_OUTPUT
          echo "$body" >> $GITHUB_OUTPUT
          echo "$delimiter" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: ${{ !inputs.dry_run }}
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          delete-branch: true
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          branch: release/${{ steps.run-release.outputs.new_version }}
          title: '🚀 Release/v${{ steps.run-release.outputs.new_version }}'
          body: |
            ${{ steps.get-pr-body.outputs.body }}

            ---

            > **DO NOT SQUASH OR REBASE ME**
            >
            > If this PR is merged with squash or rebase, the tag may be lost because the tag is already attached to the original release commit SHA.

      - name: Create GitHub Release
        if: ${{ !inputs.dry_run && inputs.mode != 'prerelease' }}
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          name: Release ${{ steps.generate_body.outputs.tag_name }}
          tag: ${{ steps.generate_body.outputs.tag_name }}
          commit: ${{ github.head_ref || github.ref_name }}
          bodyFile: RELEASE_BODY.md
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push tag
        if: ${{ !inputs.dry_run }}
        run: git push origin "tag" "v${{ steps.run-release.outputs.new_version }}" || echo ""

      - name: Dry run summary
        if: ${{ inputs.dry_run }}
        run: |
          echo "Dry run completed"
          echo "Calculated version: ${{ steps.run-release.outputs.new_version }}"
