name: 🚀 Deploy / preview

on:
  pull_request:
  workflow_dispatch:

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ !contains(github.head_ref, 'release/') }}
    name: Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: taiga-family/actions/setup-variables@6b70ab6d36d96e388bdaf4158e6dd841430abe23 # v2.3.0
      - uses: taiga-family/actions/setup-node@6b70ab6d36d96e388bdaf4158e6dd841430abe23 # v2.3.0
      - run: npx nx build demo
      - name: Debug output
        run: tree dist/demo/browser -P '*.html'

      - name: Prepare Firebase channel id
        if: env.IS_OWNER_MODE == 'true'
        shell: bash
        env:
          PR_NUMBER: ${{ github.event.number }}
          HEAD_REF: ${{ github.head_ref }}
        run: |
          RAW="pr${PR_NUMBER}-${HEAD_REF}-demo"

          CHANNEL_ID="$(echo "$RAW" \
            | tr '[:upper:]' '[:lower:]' \
            | sed -E 's/[^a-z0-9-]+/-/g; s/^-+|-+$//g; s/-+/-/g' \
            | cut -c1-63)"

          echo "FIREBASE_CHANNEL_ID=$CHANNEL_ID" >> "$GITHUB_ENV"
          echo "Firebase channel: $CHANNEL_ID"

      - name: Deploy preview
        if: env.IS_OWNER_MODE == 'true'
        uses: w9jds/firebase-action@v15.22.2
        with:
          args:
            hosting:channel:deploy "$FIREBASE_CHANNEL_ID" --project taiga-preview-demo --only taiga-preview-demo
            --expires 1d --non-interactive
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_TAIGA_PREVIEWS_SA }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
