name: 🚀 Deploy / preview
on:
  pull_request:
  workflow_dispatch:

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ !contains(github.head_ref, 'release/') }}
    name: Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: taiga-family/actions/setup-variables@6b70ab6d36d96e388bdaf4158e6dd841430abe23 # v2.3.0
      - uses: taiga-family/actions/setup-node@6b70ab6d36d96e388bdaf4158e6dd841430abe23 # v2.3.0
      - run: npx nx build demo
      - name: Debug output
        run: tree dist/demo/browser -P '*.html'
      - uses: taiga-family/actions/setup-node@6b70ab6d36d96e388bdaf4158e6dd841430abe23 # v2.3.0
        if: env.IS_OWNER_MODE == 'true'
        with:
          node-version: 24.x # https://github.com/FirebaseExtended/action-hosting-deploy/issues/440
          validate-peer-deps: false
      - name: Deploy preview
        uses: FirebaseExtended/action-hosting-deploy@e2eda2e106cfa35cdbcf4ac9ddaf6c4756df2c8c # v0.10.0
        if: env.IS_OWNER_MODE == 'true'
        with:
          channelId: pr${{ github.event.number }}-${{ github.head_ref }}-demo
          firebaseServiceAccount: ${{ secrets.FIREBASE_TAIGA_PREVIEWS_SA }}
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseToolsVersion: 15.8.0
          projectId: taiga-preview-demo
          target: taiga-preview-demo
          expires: 1d

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
