name: 🗂 Collect Linked Issues on PR Close
on:
  pull_request:
    types: [closed]

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR was merged
        id: check-merge
        run: |
          if [ "${{ github.event.pull_request.merged }}" == "true" ]; then
            echo "should_proceed=true" >> $GITHUB_OUTPUT
          else
            echo "should_proceed=false" >> $GITHUB_OUTPUT
          fi

      - name: Find ALL linked issues
        if: steps.check-merge.outputs.should_proceed == 'true'
        id: find-linked-issues
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body || '';
            const prNumber = context.payload.pull_request.number;

            const fromBody = [...body.matchAll(/#(\d+)/g)].map(m => Number(m[1]));

            const { data: timelineEvents } = await github.rest.issues.listEventsForTimeline({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });

            const fromTimeline = timelineEvents
              .filter(event => event.event === 'cross-referenced')
              .filter(event => event.source?.issue?.number)
              .map(event => event.source.issue.number);

            const linkedIssues = [...new Set([...fromBody, ...fromTimeline])];

            console.log(linkedIssues.length
              ? `Found linked issues: ${linkedIssues.join(', ')}`
              : 'No linked issues found.');

            return JSON.stringify(linkedIssues);

      - name: Dispatch to Assign workflow
        if: steps.check-merge.outputs.should_proceed == 'true'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          event-type: assign-issues
          client-payload: |
            {
              "linkedIssues": ${{ steps.find-linked-issues.outputs.result }},
              "prAuthor": "${{ github.event.pull_request.user.login }}",
              "prNumber": "${{ github.event.pull_request.number }}"
            }
