name: ⚠️ Publish Taiga UI packages
on:
  push:
    branches: ['release/*']

permissions:
  contents: read

env:
  NX_DISABLE_NX_CACHE: true
  NX_DISABLE_REMOTE_CACHE: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - uses: taiga-family/actions/setup-variables@a11d89eb978fe572206a7b0a026b38ae957acba0 # v2.0.0
      - uses: taiga-family/actions/setup-node@a11d89eb978fe572206a7b0a026b38ae957acba0 # v2.0.0
      - uses: taiga-family/actions/setup-npm@a11d89eb978fe572206a7b0a026b38ae957acba0 # v2.0.0
        with:
          token: ${{ secrets.TAIGA_UI_SCOPE_NPM_TOKEN }}

      - run: npx nx run-many -t publish

      - uses: taiga-family/actions/read-package-json@a11d89eb978fe572206a7b0a026b38ae957acba0 # v2.0.0
        id: info

      - name: Announce to Time messenger
        uses: taiga-family/actions/messenger-mattermost-announce@a11d89eb978fe572206a7b0a026b38ae957acba0 # v2.0.0
        if: ${{ !contains(steps.info.outputs.version, 'rc') }}
        with:
          url: ${{ secrets.ANNOUNCE_WEBHOOK }}
          channel: ${{ secrets.ANNOUNCE_TARGET }}
          version: v${{ steps.info.outputs.version }}

      - name: Announce to Telegram messenger
        uses: taiga-family/actions/messenger-telegram-announce@a11d89eb978fe572206a7b0a026b38ae957acba0 # v2.0.0
        if: ${{ !contains(steps.info.outputs.version, 'rc') }}
        with:
          chatId: ${{ secrets.TAIGA_TELEGRAM_CHAT_ID }}
          topicId: ${{ secrets.TAIGA_TELEGRAM_CHAT_THREAD_ID }}
          token: ${{ secrets.TAIGA_TELEGRAM_BOT_TOKEN }}
          version: v${{ steps.info.outputs.version }}
          textLink: '@taiga-ui/cdk'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
