name: ⚠️ Publish canary
on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 1-5' # At UTC 20:00 (MSK 23:00) on every day-of-week from Monday through Friday

permissions:
  contents: read
  packages: write

env:
  NX_DISABLE_NX_CACHE: true
  NX_DISABLE_REMOTE_CACHE: true

jobs:
  publish-canary:
    runs-on: ubuntu-latest
    name: Publish canary
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: taiga-family/ci/actions/setup/variables@v1.195.0
      - uses: taiga-family/ci/actions/setup/node@v1.195.0
      - name: Configure GitHub Packages registry for @taiga-ui scope
        run: |
          echo "@taiga-ui:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npx ts-node ./scripts/publish-canary.ts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
