name: ⚠️ Publish canary
on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 1-5' # At UTC 20:00 (MSK 23:00) on every day-of-week from Monday through Friday

permissions:
  contents: read

env:
  NX_DISABLE_NX_CACHE: true
  NX_DISABLE_REMOTE_CACHE: true

jobs:
  publish-canary:
    runs-on: ubuntu-latest
    name: Publish canary
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: taiga-family/ci/actions/setup/variables@41a6dcaf21b0a83a93310de63dde18583feb5920 # v1.210.0
      - uses: taiga-family/ci/actions/setup/node@41a6dcaf21b0a83a93310de63dde18583feb5920 # v1.210.0
      - uses: taiga-family/ci/actions/setup/config/npm@41a6dcaf21b0a83a93310de63dde18583feb5920 # v1.210.0
        with:
          token: ${{ secrets.TAIGA_UI_SCOPE_NPM_TOKEN }}
      - run: npx ts-node ./scripts/publish-canary.ts

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
