name: ⚠️ Publish canary
on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 1-5' # At UTC 20:00 (MSK 23:00) on every day-of-week from Monday through Friday

permissions:
  contents: read

env:
  NX_DISABLE_NX_CACHE: true
  NX_DISABLE_REMOTE_CACHE: true

jobs:
  publish-canary:
    runs-on: ubuntu-latest
    name: Publish canary
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: taiga-family/ci/actions/setup/variables@a173bbdd44beec5cb34444b6fa497284da803031 # v1.217.0
      - uses: taiga-family/ci/actions/setup/node@a173bbdd44beec5cb34444b6fa497284da803031 # v1.217.0
      - uses: taiga-family/ci/actions/setup/config/npm@a173bbdd44beec5cb34444b6fa497284da803031 # v1.217.0
        with:
          token: ${{ secrets.TAIGA_UI_SCOPE_NPM_TOKEN }}
      - run: npx ts-node ./scripts/publish-canary.ts

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
