name: ⚙️ Schematics
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/taiga-schematics/**'
      - '**/schematics/**'

permissions:
  contents: read

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  schematics:
    if: ${{ !contains(github.head_ref , 'release/') }}
    runs-on: ubuntu-latest
    name: Run the latest migration
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: taiga-family/actions/setup-node@a11d89eb978fe572206a7b0a026b38ae957acba0 # v2.0.0
      - uses: taiga-family/actions/get-node-info@a11d89eb978fe572206a7b0a026b38ae957acba0 # v2.0.0
        id: info
      - run: npx nx run cdk:schematics --v=${{ steps.info.outputs.root-package-major-version }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
