name: ⚙️ Schematics
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/taiga-schematics/**'
      - '**/schematics/**'

permissions:
  contents: read

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  schematics:
    if: ${{ !contains(github.head_ref , 'release/') }}
    runs-on: ubuntu-latest
    name: Run the latest migration
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: taiga-family/actions/setup-node@9b6ebca664f44d0fc34a50bec5f85becdf27d388 # v2.12.0
      - uses: taiga-family/actions/get-node-info@9b6ebca664f44d0fc34a50bec5f85becdf27d388 # v2.12.0
        id: info
      - run: npx nx run cdk:schematics --v=${{ steps.info.outputs.root-package-major-version }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
