name: ⚙️ Schematics
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/taiga-schematics/**'
      - '**/schematics/**'

permissions:
  contents: read

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  schematics:
    if: ${{ !contains(github.head_ref , 'release/') }}
    runs-on: ubuntu-latest
    name: Run the latest migration
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: taiga-family/ci/actions/setup/node@e9c5cd341c28d9aeb357b757df41cddcbb674b2d # v1.222.0
      - uses: taiga-family/ci/actions/run/node-info@e9c5cd341c28d9aeb357b757df41cddcbb674b2d # v1.222.0
        id: info
      - run: npx nx run cdk:schematics --v=${{ steps.info.outputs.root-package-major-version }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
