name: 🚀 Snapshots
on:
  push:
    branches: [main, 'v[0-9]+.x', 'release/**']
  workflow_dispatch:
    inputs:
      updateMain:
        type: boolean
        required: false
        description: update main snapshots

permissions:
  contents: read

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  next-snapshot:
    name: Push next snapshot
    if: ${{ !contains(github.head_ref || github.ref_name, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: taiga-family/ci/actions/setup/variables@c5bcf64b54eb51e9274fa667e69cfd0d2f37adfd # v1.209.0
      - uses: taiga-family/ci/actions/setup/node@c5bcf64b54eb51e9274fa667e69cfd0d2f37adfd # v1.209.0

      - run: npx nx build demo
      - run: tree ${{ env.DIST }} -P '*.html'

      - uses: s0/git-publish-subdir-action@92faf786f11dfa44fc366ac3eb274d193ca1af7e # v2.6.0
        env:
          REPO: self
          FOLDER: ${{ env.DIST }}
          BRANCH: snapshots/demo/next/${{ github.head_ref || github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

  production-snapshot:
    name: Push production snapshot
    if: ${{ contains(github.head_ref || github.ref_name, 'release/') || github.event.inputs.updateMain == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: taiga-family/ci/actions/setup/variables@c5bcf64b54eb51e9274fa667e69cfd0d2f37adfd # v1.209.0
      - uses: taiga-family/ci/actions/setup/node@c5bcf64b54eb51e9274fa667e69cfd0d2f37adfd # v1.209.0
        id: nodejs-workspace

      - run: npx nx build demo
      - run: tree ${{ env.DIST }} -P '*.html'

      - uses: s0/git-publish-subdir-action@92faf786f11dfa44fc366ac3eb274d193ca1af7e # v2.6.0
        env:
          REPO: self
          FOLDER: ${{ env.DIST }}
          BRANCH: snapshots/demo/v${{ steps.nodejs-workspace.outputs.root-package-major-version }}.x
          GITHUB_TOKEN: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
