name: 🚀 Snapshots
on:
  push:
    branches: [main, 'v[0-9]+.x', 'release/**']
  workflow_dispatch:
    inputs:
      updateMain:
        type: boolean
        required: false
        description: update main snapshots

permissions:
  contents: read

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  next-snapshot:
    name: Push next snapshot
    if: ${{ !contains(github.head_ref || github.ref_name, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: taiga-family/ci/actions/setup/variables@a173bbdd44beec5cb34444b6fa497284da803031 # v1.217.0
      - uses: taiga-family/ci/actions/setup/node@a173bbdd44beec5cb34444b6fa497284da803031 # v1.217.0

      - run: npx nx build demo
      - run: tree ${{ env.DIST }} -P '*.html'

      - uses: s0/git-publish-subdir-action@92faf786f11dfa44fc366ac3eb274d193ca1af7e # v2.6.0
        env:
          REPO: self
          FOLDER: ${{ env.DIST }}
          BRANCH: snapshots/demo/next/${{ github.head_ref || github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

  production-snapshot:
    name: Push production snapshot
    if: ${{ contains(github.head_ref || github.ref_name, 'release/') || github.event.inputs.updateMain == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: taiga-family/ci/actions/setup/variables@a173bbdd44beec5cb34444b6fa497284da803031 # v1.217.0
      - uses: taiga-family/ci/actions/setup/node@a173bbdd44beec5cb34444b6fa497284da803031 # v1.217.0
        id: nodejs-workspace

      - run: npx nx build demo
      - run: tree ${{ env.DIST }} -P '*.html'

      - uses: s0/git-publish-subdir-action@92faf786f11dfa44fc366ac3eb274d193ca1af7e # v2.6.0
        env:
          REPO: self
          FOLDER: ${{ env.DIST }}
          BRANCH: snapshots/demo/v${{ steps.nodejs-workspace.outputs.root-package-major-version }}.x
          GITHUB_TOKEN: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
