name: ⚙️ Unit tests
on:
  pull_request:
  push:
    branches: [main, 'v[0-9]+.x']

permissions:
  contents: read

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  test:
    if: ${{ !contains(github.head_ref, 'release/') }}
    name: Tests result
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: taiga-family/actions/setup-variables@5b954545ec33833478961976b2ce4fd3c6b89149 # v2.7.0
      - uses: taiga-family/actions/setup-node@5b954545ec33833478961976b2ce4fd3c6b89149 # v2.7.0
      - run: npm test
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          directory: ./coverage/
          flags: summary
          name: units

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
